version: "2.0"

networks:
    apt:
        # use the bridge driver, but enable IPv6
        driver: bridge

services:

  client:
    image: ubuntu:xenial
    container_name: uuu
    command: tail -f /dev/null
    networks:
      - apt

  reprepro:
    image: reprepro
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: rrr
    working_dir: /var/repositories
    command: tail -f /dev/null
    networks:
      - apt
    volumes:
      # nginx ayarları
      - ./volume/reprepro/default:/etc/nginx/sites-available/default
      # reprepro conf dizini (icinde incomig, distributions, options... dosyaları var)
      - ./volume/reprepro/conf:/var/repositories/conf/
      # dışarıdan gelen ve taranarak repoya alınacak deb dosyalarının karşılandığı ana dizin
      - ./volume/reprepro/incoming:/var/repositories/incoming
      # dağıtımların Release dosyalarının tutulduğu ana dizin
      - ./volume/reprepro/dists:/var/repositories/dists
      # taradıkça güncellenen veritabanı
      - ./volume/reprepro/db:/var/repositories/db
      # .deb paketlerinin dizinler halinde saklandığı ana dizin 
      - ./volume/reprepro/pool:/var/repositories/pool
